version: "2.1"
services:
  playlistSync:
    image: dregsozworld/plex_playlist_sync
    container_name: playlistSync

    volumes:
      - <directory where csv stored>:/data
    environment:
      - PLEX_URL= <Your local plex url>
      - PLEX_TOKEN=<Your token>
      - WRITE_MISSING_AS_CSV=<1 | 0 >
      - APPEND_SERVICE_SUFFIX= <1 | 0>
      - ADD_PLAYLIST_POSTER= ><1 | 0 >
      - ADD_PLAYLIST_DESCRIPTION= < 1 | 0 >
      - APPEND_INSTEAD_OF_SYNC= <1 | 0 >
      - SECONDS_TO_WAIT=43200  #12 Hours Default
      - SPOTIFY_CLIENT_ID= <Your ID>
      - SPOTIFY_CLIENT_SECRET= <Your Secret>
      - SPOTIFY_USER_ID= <Your ID / Username >
      - DEEZER_USER_ID=<your spotify user id>
      - DEEZER_PLAYLIST_ID= # multiple playlists are space separated
    restart: unless-stopped