---
version: "2.1"
services:
  playlistSync:
    image: rnagabhyrava/plexplaylistsync:latest
    container_name: playlistSync
    environment:
      - PLEX_URL=http://192.99.99.99:32400
      - PLEX_TOKEN=qwertyuiop
      - SPOTIPY_CLIENT_ID=qwertyuiop # Optional
      - SPOTIPY_CLIENT_SECRET=qwertyuiop # Optional
      - SPOTIFY_USER_ID=qwertyuiop # Optional
      - DEEZER_USER_ID=9999999999 # Optional
      - DEEZER_PLAYLIST_ID=1313621735 1963962142 # Optional
      - SECONDS_TO_WAIT=86400
    restart: unless-stopped